name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2

      - name: Make init-npm.sh executable
        run: chmod +x ./init-npm.sh

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - run: ./init-npm.sh harena-store npm-hei-school 088312068315 eu-west-3

      - name: Install Husky
        run: npm install husky --save-dev

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier
        run: npm run format && npm run format:check

      - name: Run Build
        run: npm run build
