name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: rm package.json package-lock.json
      - run: |
          npm init -y
          npm install -d prettier prettier-plugin-organize-imports
      - run: npx prettier --write "src/**/*.{js,ts,tsx}" "./**/*.{json,yml,yaml}"