name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2

      - run: ./init-npm.sh  harena-store npm-hei-school 088312068315 eu-west-3

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier
        run: npm run format && npm run format:check

      - name: Run Eslint
        run: npm run lint

      - name: Run Build
        run: npm run build
